spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/db2021?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
